# Generated by Django 5.2.7 on 2025-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disney_app', '0002_alter_coders_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coders',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
